name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint --filter react-responsive-modal

      - name: Test
        run: pnpm run lint test --ci --coverage --maxWorkers=2 --filter react-responsive-modal

      - name: Report coverage
        uses: codecov/codecov-action@v1

      - name: Build
        run: pnpm run build --filter react-responsive-modal

      - name: Build docs
        run: pnpm run build --filter website

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Dependencies already installed before
          install: false
          # Use monorepo
          project: ./react-responsive-modal
          start: pnpm run start -p 3000 --filter website
